import 'app_language.dart';

String quickText(String key) =>
    _strings[appLanguage.code]?[key] ?? _strings['en']?[key] ?? key;

const Map<String, Map<String, String>> _strings = {
  'en': {
    'languageTitle': 'Choose your preferred language',
    'languageQuestion': 'Which language would you like to use this app in?',
    'title': "Let's get started",
    'subtitle': 'Join with your name and mobile contact number.',
    'mobile': 'Mobile contact number',
    'mobileHint': '10 digits, or +91 followed by 10 digits',
    'invalidMobile':
        'Enter a valid 10-digit Indian mobile number starting with 6–9.',
    'invalidForm': 'Check your name and mobile number, then try again.',
    'mobileNotice': 'No OTP is sent. This number is an unverified contact detail, not a login or recovery method.',
    'sessionInvalid': 'This saved sign-in is no longer valid. Ask the developer to reset this test session safely; preserve any needed local drafts first.',
    'name': 'Enter your name',
    'hint': 'Example: Ram Kumar',
    'start': 'Continue',
    'working': 'Saving your profile…',
    'invalidName': 'Enter a name with 2–100 characters.',
    'slogan': 'Not waste.\nA better tomorrow.',
    'consent': 'By tapping Continue, you agree to saving your name, unverified mobile contact number, role and language in Firebase for your account.',
    'guestWarning': 'Guest access stays on this app installation. Until recovery is linked, clearing app data, uninstalling or losing the phone can mean losing access to your records.',
    'existingNote': 'Already signed in? Your existing account and stored profile are kept. Entering different details here will not create another account or edit the existing one.',
    'online': 'Internet is required to confirm this profile step.',
    'slow': 'This is taking longer than expected. Check your connection. No success has been confirmed yet.',
    'network': 'The profile could not be confirmed online. Check your connection, then try again. Do not clear app data.',
    'disabled': 'Enable Anonymous sign-in in Firebase Authentication.',
    'denied': 'Profile access denied. Publish the matching name/mobile contact Firestore rules.',
    'limited': 'Too many requests. Wait before trying again.',
    'failed': 'Could not finish. Try again or share the error code with the developer.',
    'ready': 'Profile ready',
    'restored': 'Existing profile kept',
    'role': 'Role',
    'collector': 'Collector',
    'recycler': 'Recycler',
    'guest': 'Guest account',
    'linked': 'Existing signed-in account',
    'pending': 'Recycler authorization: pending review',
    'dashboardPending':
        'Registration is ready. The home screen will be built next.',
    'recoveryLater': 'Account-recovery linking is planned. It is not available on this screen yet.',
    'preserved': 'Your original profile was loaded; its name, role and authorization status were not overwritten.',
  },

  'hi': {
    'languageTitle': 'अपनी पसंद की भाषा चुनें',
    'languageQuestion': 'आप इस ऐप को किस भाषा में उपयोग करना चाहते हैं?',
    'title': 'चलिए शुरू करते हैं',
    'subtitle': 'अपने नाम और मोबाइल संपर्क नंबर के साथ जुड़ें।',
    'mobile': 'मोबाइल संपर्क नंबर',
    'mobileHint': '10 अंक, या +91 के बाद 10 अंक',
    'invalidMobile':
        '6–9 से शुरू होने वाला सही 10 अंकों का भारतीय मोबाइल नंबर दर्ज करें।',
    'invalidForm': 'अपना नाम और मोबाइल नंबर जाँचें, फिर दोबारा कोशिश करें।',
    'mobileNotice': 'कोई OTP नहीं भेजा जाएगा। यह नंबर केवल अप्रमाणित संपर्क विवरण है, लॉगिन या खाता रिकवरी का तरीका नहीं है।',
    'sessionInvalid': 'यह सेव किया हुआ साइन-इन अब मान्य नहीं है। जरूरी स्थानीय ड्राफ्ट सुरक्षित रखने के बाद डेवलपर से इस टेस्ट सेशन को सुरक्षित तरीके से रीसेट करवाएँ।',
    'name': 'अपना नाम दर्ज करें',
    'hint': 'उदाहरण: राम कुमार',
    'start': 'आगे बढ़ें',
    'working': 'आपकी प्रोफ़ाइल सेव हो रही है…',
    'invalidName': '2–100 अक्षरों वाला नाम दर्ज करें।',
    'slogan': 'कचरा नहीं।\nबेहतर कल की शुरुआत।',
    'consent': 'आगे बढ़ें दबाकर आप अपने खाते के लिए नाम, अप्रमाणित मोबाइल संपर्क नंबर, भूमिका और भाषा Firebase में सेव करने की सहमति देते हैं।',
    'guestWarning': 'गेस्ट खाते का प्रवेश इसी ऐप इंस्टॉलेशन तक सीमित रहता है। रिकवरी लिंक होने तक ऐप डेटा मिटाने, ऐप हटाने या फोन खोने से आपके रिकॉर्ड तक पहुँच समाप्त हो सकती है।',
    'existingNote': 'पहले से साइन इन हैं? आपका मौजूदा खाता और सेव की गई प्रोफ़ाइल सुरक्षित रखी जाएगी। यहाँ अलग जानकारी दर्ज करने से नया खाता नहीं बनेगा और पुरानी प्रोफ़ाइल बदली नहीं जाएगी।',
    'online': 'इस प्रोफ़ाइल चरण की पुष्टि के लिए इंटरनेट आवश्यक है।',
    'slow': 'इसमें अपेक्षा से अधिक समय लग रहा है। अपना कनेक्शन जाँचें। अभी सफलता की पुष्टि नहीं हुई है।',
    'network': 'प्रोफ़ाइल की ऑनलाइन पुष्टि नहीं हो सकी। कनेक्शन जाँचकर दोबारा कोशिश करें। ऐप डेटा न मिटाएँ।',
    'disabled': 'Firebase Authentication में Anonymous sign-in सक्षम करें।',
    'denied': 'प्रोफ़ाइल की अनुमति नहीं मिली। नाम/मोबाइल संपर्क वाले नए Firestore rules प्रकाशित करें।',
    'limited': 'बहुत अधिक अनुरोध हुए हैं। थोड़ी देर बाद दोबारा कोशिश करें।',
    'failed': 'प्रक्रिया पूरी नहीं हो सकी। दोबारा कोशिश करें या error code डेवलपर को भेजें।',
    'ready': 'प्रोफ़ाइल तैयार है',
    'restored': 'मौजूदा प्रोफ़ाइल सुरक्षित रखी गई',
    'role': 'भूमिका',
    'collector': 'कबाड़ संग्राहक',
    'recycler': 'रीसायकलकर्ता',
    'guest': 'गेस्ट खाता',
    'linked': 'पहले से साइन-इन किया हुआ खाता',
    'pending': 'रीसायकलकर्ता की अनुमति: समीक्षा बाकी है',
    'dashboardPending':
        'पंजीकरण तैयार है। होम स्क्रीन अगले चरण में बनाई जाएगी।',
    'recoveryLater': 'खाता रिकवरी लिंक करना आगे की योजना में है। यह अभी इस स्क्रीन पर उपलब्ध नहीं है।',
    'preserved': 'आपकी मूल प्रोफ़ाइल लोड की गई है; उसका नाम, भूमिका और अनुमति की स्थिति नहीं बदली गई।',
  },

  'mr': {
    'languageTitle': 'तुमच्या पसंतीची भाषा निवडा',
    'languageQuestion': 'तुम्हाला हे अॅप कोणत्या भाषेत वापरायचे आहे?',
    'title': 'चला, सुरुवात करूया',
    'subtitle': 'तुमचे नाव आणि मोबाईल संपर्क क्रमांक देऊन सहभागी व्हा.',
    'mobile': 'मोबाईल संपर्क क्रमांक',
    'mobileHint': '10 अंक, किंवा +91 नंतर 10 अंक',
    'invalidMobile':
        '6–9 ने सुरू होणारा योग्य 10 अंकी भारतीय मोबाईल क्रमांक प्रविष्ट करा.',
    'invalidForm': 'तुमचे नाव आणि मोबाईल क्रमांक तपासा आणि पुन्हा प्रयत्न करा.',
    'mobileNotice': 'कोणताही OTP पाठवला जाणार नाही. हा क्रमांक केवळ अप्रमाणित संपर्क तपशील आहे; लॉगिन किंवा खाते पुनर्प्राप्तीसाठी वापरला जाणार नाही.',
    'sessionInvalid': 'हा सेव्ह केलेला साइन-इन आता वैध नाही. आवश्यक स्थानिक ड्राफ्ट सुरक्षित ठेवल्यानंतर डेव्हलपरकडून हे टेस्ट सेशन सुरक्षितपणे रीसेट करून घ्या.',
    'name': 'तुमचे नाव प्रविष्ट करा',
    'hint': 'उदाहरण: राम कुमार',
    'start': 'पुढे जा',
    'working': 'तुमची प्रोफाइल सेव्ह करत आहोत…',
    'invalidName': '2–100 अक्षरांचे नाव प्रविष्ट करा.',
    'slogan': 'कचरा नाही.\nउत्तम उद्याची सुरुवात.',
    'consent': 'पुढे जा दाबून तुम्ही तुमच्या खात्यासाठी नाव, अप्रमाणित मोबाईल संपर्क क्रमांक, भूमिका आणि भाषा Firebase मध्ये सेव्ह करण्यास संमती देता.',
    'guestWarning': 'गेस्ट खात्याचा प्रवेश या अॅपच्या इंस्टॉलेशनपुरता मर्यादित आहे. रिकव्हरी लिंक होईपर्यंत अॅप डेटा हटवल्यास, अॅप अनइन्स्टॉल केल्यास किंवा फोन हरवल्यास तुमच्या नोंदींवरील प्रवेश गमावला जाऊ शकतो.',
    'existingNote': 'आधीच साइन इन केले आहे? तुमचे विद्यमान खाते आणि सेव्ह केलेली प्रोफाइल सुरक्षित ठेवली जाईल. येथे वेगळी माहिती दिल्याने नवीन खाते तयार होणार नाही आणि जुनी प्रोफाइल बदलली जाणार नाही.',
    'online': 'या प्रोफाइल चरणाची पुष्टी करण्यासाठी इंटरनेट आवश्यक आहे.',
    'slow': 'याला अपेक्षेपेक्षा जास्त वेळ लागत आहे. तुमचे कनेक्शन तपासा. अद्याप यशाची पुष्टी झालेली नाही.',
    'network': 'प्रोफाइलची ऑनलाइन पुष्टी होऊ शकली नाही. कनेक्शन तपासून पुन्हा प्रयत्न करा. अॅप डेटा हटवू नका.',
    'disabled': 'Firebase Authentication मध्ये Anonymous sign-in सक्षम करा.',
    'denied': 'प्रोफाइल प्रवेश नाकारला. नाव/मोबाईल संपर्कासाठी नवीन Firestore rules प्रकाशित करा.',
    'limited':
        'खूप जास्त विनंत्या झाल्या आहेत. थोड्या वेळाने पुन्हा प्रयत्न करा.',
    'failed': 'प्रक्रिया पूर्ण होऊ शकली नाही. पुन्हा प्रयत्न करा किंवा error code डेव्हलपरला पाठवा.',
    'ready': 'प्रोफाइल तयार आहे',
    'restored': 'विद्यमान प्रोफाइल सुरक्षित ठेवली आहे',
    'role': 'भूमिका',
    'collector': 'भंगार संकलक',
    'recycler': 'पुनर्वापरकर्ता',
    'guest': 'गेस्ट खाते',
    'linked': 'आधीपासून साइन-इन केलेले खाते',
    'pending': 'पुनर्वापरकर्त्याची परवानगी: पुनरावलोकन बाकी आहे',
    'dashboardPending':
        'नोंदणी तयार आहे. होम स्क्रीन पुढील टप्प्यात तयार केली जाईल.',
    'recoveryLater': 'खाते रिकव्हरी लिंक करणे पुढील योजनेत आहे. हे सध्या या स्क्रीनवर उपलब्ध नाही.',
    'preserved': 'तुमची मूळ प्रोफाइल लोड केली आहे; तिचे नाव, भूमिका आणि परवानगीची स्थिती बदललेली नाही.',
  },
};
