import 'app_language.dart';

String registrationText(String key) =>
    _texts[appLanguage.code]?[key] ?? _texts['en']?[key] ?? key;

const Map<String, Map<String, String>> _texts = {
  'en': {
    'title': "Let's get started",
    'loginTitle': 'Welcome back',
    'subtitle': 'Create your account with email and password',
    'loginSubtitle': 'Sign in to your existing account',
    'name': 'Your full name',
    'nameHint': 'Example: Ram Kumar',
    'nameError': 'Enter a name with 2–100 characters.',
    'email': 'Email address',
    'emailHint': 'you@example.com',
    'emailError': 'Enter a valid email address.',
    'password': 'Password',
    'passwordHint': 'At least 8 characters for a new account',
    'passwordError': 'Use at least 8 characters for a new account.',
    'passwordRequired': 'Enter your password.',
    'confirm': 'Confirm password',
    'confirmError': 'The passwords do not match.',
    'showPassword': 'Show password',
    'hidePassword': 'Hide password',
    'consent': 'I agree to storing my name, email, selected role and language in Firebase to provide my account. Never enter someone else’s email address.',
    'consentError': 'Please agree to account data storage first.',
    'internet':
        'Internet is required for sign-up and sign-in. No SMS OTP is used.',
    'create': 'Create account',
    'login': 'Sign in',
    'working': 'Please wait…',
    'retry': 'Retry saving profile',
    'saveFailed': 'Your account is authenticated, but saving the profile was not confirmed. Retry saving; no new account is needed.',
    'existingAccount': 'Already have an account? Sign in',
    'newAccount': 'New here? Create an account',
    'forgot': 'Forgot password?',
    'resetSent': 'If this email has a supported account, a password-reset email will be sent. Check your inbox and spam folder.',
    'network': 'Check your internet connection and try again.',
    'emailInUse': 'This email may already have an account. Try Sign in or Forgot password.',
    'weakPassword': 'This password does not meet the project’s password policy. Choose a stronger password.',
    'invalidLogin': 'Unable to sign in. Check your email and password.',
    'limited': 'Too many attempts. Please try later.',
    'setup': 'Enable Email/Password in Firebase Authentication.',
    'permission':
        'Profile access denied. Publish the email-profile Firestore rules.',
    'generic': 'The request failed. Please try again.',
    'saved': 'Profile saved',
    'existing': 'Existing profile loaded',
    'existingNote': 'The account’s original role has been preserved.',
    'role': 'Role',
    'collector': 'Collector',
    'recycler': 'Recycler',
    'pending': 'Recycler authorization: pending review',
    'notDashboard':
        'Your profile is stored in Firebase. The dashboard will be added next.',
    'emailVerified': 'Email verified',
    'emailUnverified': 'Email not yet verified',
    'sendVerification': 'Send verification email',
    'verificationSent': 'Verification email requested. Check your inbox/spam, follow the link, then refresh status.',
    'refreshVerification': 'Refresh verification status',
    'verifyWait': 'Please wait before requesting another verification email.',
    'changeLanguage': 'Language',
  },
  'hi': {
    'title': 'चलो शुरू करें',
    'loginTitle': 'वापस स्वागत है',
    'subtitle': 'ईमेल और पासवर्ड से खाता बनाएँ',
    'loginSubtitle': 'अपने मौजूदा खाते में साइन इन करें',
    'name': 'अपना पूरा नाम दर्ज करें',
    'nameHint': 'उदाहरण: राम कुमार',
    'nameError': '2–100 अक्षरों का नाम दर्ज करें।',
    'email': 'ईमेल पता',
    'emailHint': 'you@example.com',
    'emailError': 'सही ईमेल पता दर्ज करें।',
    'password': 'पासवर्ड',
    'passwordHint': 'नए खाते के लिए कम से कम 8 अक्षर',
    'passwordError': 'नए खाते के लिए कम से कम 8 अक्षरों का पासवर्ड रखें।',
    'passwordRequired': 'पासवर्ड दर्ज करें।',
    'confirm': 'पासवर्ड दोबारा दर्ज करें',
    'confirmError': 'दोनों पासवर्ड मेल नहीं खाते।',
    'showPassword': 'पासवर्ड दिखाएँ',
    'hidePassword': 'पासवर्ड छिपाएँ',
    'consent': 'खाता उपलब्ध कराने के लिए मैं अपना नाम, ईमेल, भूमिका और भाषा Firebase में सहेजने के लिए सहमत हूँ। किसी और का ईमेल दर्ज न करें।',
    'consentError': 'पहले खाते की जानकारी सहेजने की सहमति दें।',
    'internet': 'खाता बनाने और साइन इन के लिए इंटरनेट आवश्यक है। SMS OTP का उपयोग नहीं होता।',
    'create': 'खाता बनाएँ',
    'login': 'साइन इन करें',
    'working': 'कृपया प्रतीक्षा करें…',
    'retry': 'प्रोफ़ाइल दोबारा सहेजें',
    'saveFailed': 'खाते का प्रमाणीकरण हुआ, लेकिन प्रोफ़ाइल सहेजने की पुष्टि नहीं मिली। दोबारा सहेजें; नया खाता बनाने की जरूरत नहीं।',
    'existingAccount': 'पहले से खाता है? साइन इन करें',
    'newAccount': 'नए हैं? खाता बनाएँ',
    'forgot': 'पासवर्ड भूल गए?',
    'resetSent': 'यदि इस ईमेल का समर्थित खाता है, तो पासवर्ड रीसेट ईमेल भेजा जाएगा। इनबॉक्स और स्पैम जाँचें।',
    'network': 'इंटरनेट कनेक्शन जाँचकर दोबारा कोशिश करें।',
    'emailInUse':
        'इस ईमेल का खाता पहले से हो सकता है। साइन इन या पासवर्ड रीसेट करें।',
    'weakPassword': 'पासवर्ड परियोजना की सुरक्षा नीति से मेल नहीं खाता। अधिक मजबूत पासवर्ड चुनें।',
    'invalidLogin': 'साइन इन नहीं हुआ। ईमेल और पासवर्ड जाँचें।',
    'limited': 'बहुत अधिक प्रयास हुए। बाद में कोशिश करें।',
    'setup': 'Firebase Authentication में Email/Password सक्षम करें।',
    'permission': 'प्रोफ़ाइल की अनुमति नहीं मिली। ईमेल वाले Firestore rules प्रकाशित करें।',
    'generic': 'अनुरोध विफल हुआ। दोबारा कोशिश करें।',
    'saved': 'प्रोफ़ाइल सहेजी गई',
    'existing': 'मौजूदा प्रोफ़ाइल मिली',
    'existingNote': 'खाते की मूल भूमिका रखी गई है।',
    'role': 'भूमिका',
    'collector': 'कबाड़ संग्राहक',
    'recycler': 'रीसायकलकर्ता',
    'pending': 'रीसायकलकर्ता की अनुमति: समीक्षा बाकी है',
    'notDashboard': 'प्रोफ़ाइल Firebase में सहेजी गई है। डैशबोर्ड अगले चरण में जोड़ा जाएगा।',
    'emailVerified': 'ईमेल सत्यापित है',
    'emailUnverified': 'ईमेल अभी सत्यापित नहीं है',
    'sendVerification': 'सत्यापन ईमेल भेजें',
    'verificationSent': 'सत्यापन ईमेल का अनुरोध किया गया। इनबॉक्स/स्पैम में लिंक खोलें, फिर स्थिति जाँचें।',
    'refreshVerification': 'सत्यापन स्थिति जाँचें',
    'verifyWait': 'दोबारा सत्यापन ईमेल माँगने से पहले प्रतीक्षा करें।',
    'changeLanguage': 'भाषा',
  },
  'mr': {
    'title': 'चला सुरू करूया',
    'loginTitle': 'पुन्हा स्वागत आहे',
    'subtitle': 'ईमेल आणि पासवर्डने खाते तयार करा',
    'loginSubtitle': 'तुमच्या आधीच्या खात्यात साइन इन करा',
    'name': 'तुमचे पूर्ण नाव लिहा',
    'nameHint': 'उदाहरण: राम कुमार',
    'nameError': '2–100 अक्षरांचे नाव लिहा.',
    'email': 'ईमेल पत्ता',
    'emailHint': 'you@example.com',
    'emailError': 'योग्य ईमेल पत्ता लिहा.',
    'password': 'पासवर्ड',
    'passwordHint': 'नवीन खात्यासाठी किमान 8 अक्षरे',
    'passwordError': 'नवीन खात्यासाठी किमान 8 अक्षरांचा पासवर्ड वापरा.',
    'passwordRequired': 'पासवर्ड लिहा.',
    'confirm': 'पासवर्ड पुन्हा लिहा',
    'confirmError': 'दोन्ही पासवर्ड जुळत नाहीत.',
    'showPassword': 'पासवर्ड दाखवा',
    'hidePassword': 'पासवर्ड लपवा',
    'consent': 'खाते उपलब्ध करण्यासाठी माझे नाव, ईमेल, भूमिका आणि भाषा Firebase मध्ये जतन करण्यास मी सहमत आहे. दुसऱ्याचा ईमेल वापरू नका.',
    'consentError': 'आधी खात्याची माहिती जतन करण्यासाठी संमती द्या.',
    'internet':
        'नोंदणी आणि साइन इनसाठी इंटरनेट आवश्यक आहे. SMS OTP वापरला जात नाही.',
    'create': 'खाते तयार करा',
    'login': 'साइन इन करा',
    'working': 'कृपया प्रतीक्षा करा…',
    'retry': 'प्रोफाइल पुन्हा जतन करा',
    'saveFailed': 'खात्याचे प्रमाणीकरण झाले, पण प्रोफाइल जतन झाल्याची पुष्टी नाही. पुन्हा जतन करा; नवीन खाते नको.',
    'existingAccount': 'आधीच खाते आहे? साइन इन करा',
    'newAccount': 'नवीन आहात? खाते तयार करा',
    'forgot': 'पासवर्ड विसरलात?',
    'resetSent': 'या ईमेलचे समर्थित खाते असल्यास पासवर्ड रीसेट ईमेल पाठवला जाईल. इनबॉक्स आणि स्पॅम तपासा.',
    'network': 'इंटरनेट कनेक्शन तपासून पुन्हा प्रयत्न करा.',
    'emailInUse':
        'या ईमेलचे खाते आधीपासून असू शकते. साइन इन किंवा पासवर्ड रीसेट करा.',
    'weakPassword': 'पासवर्ड प्रकल्पाच्या सुरक्षा धोरणाशी जुळत नाही. अधिक मजबूत पासवर्ड निवडा.',
    'invalidLogin': 'साइन इन झाले नाही. ईमेल आणि पासवर्ड तपासा.',
    'limited': 'खूप प्रयत्न झाले. नंतर प्रयत्न करा.',
    'setup': 'Firebase Authentication मध्ये Email/Password सक्षम करा.',
    'permission':
        'प्रोफाइल प्रवेश नाकारला. ईमेलसाठीचे Firestore rules प्रकाशित करा.',
    'generic': 'विनंती अयशस्वी झाली. पुन्हा प्रयत्न करा.',
    'saved': 'प्रोफाइल जतन झाले',
    'existing': 'आधीचे प्रोफाइल मिळाले',
    'existingNote': 'खात्याची मूळ भूमिका कायम ठेवली आहे.',
    'role': 'भूमिका',
    'collector': 'भंगार संकलक',
    'recycler': 'पुनर्चक्रणकर्ता',
    'pending': 'पुनर्चक्रणकर्त्याची अधिकृतता: पुनरावलोकन बाकी',
    'notDashboard': 'प्रोफाइल Firebase मध्ये जतन झाले आहे. डॅशबोर्ड पुढच्या टप्प्यात जोडला जाईल.',
    'emailVerified': 'ईमेल पडताळला आहे',
    'emailUnverified': 'ईमेलची पडताळणी बाकी आहे',
    'sendVerification': 'पडताळणी ईमेल पाठवा',
    'verificationSent': 'पडताळणी ईमेलची विनंती केली. इनबॉक्स/स्पॅममधील लिंक उघडा आणि स्थिती तपासा.',
    'refreshVerification': 'पडताळणी स्थिती तपासा',
    'verifyWait': 'पुन्हा पडताळणी ईमेल मागण्यापूर्वी प्रतीक्षा करा.',
    'changeLanguage': 'भाषा',
  },
};
