// Isolated demo project only. Never point this suite at production.
import {readFileSync} from 'node:fs';
import {before,after,beforeEach,test} from 'node:test';
import {initializeTestEnvironment,assertSucceeds,assertFails} from '@firebase/rules-unit-testing';
import {doc,setDoc,getDoc,getDocs,collection,collectionGroup,query,where,orderBy,updateDoc,writeBatch,serverTimestamp,Timestamp,runTransaction} from 'firebase/firestore';
let env;
const profile=(role='collector',status='notApplicable')=>({name:'Test Person',role,language:'en',authorizationStatus:status,mobileNumber:'+919876543210',mobileVerified:false,createdAt:Timestamp.fromMillis(1),updatedAt:Timestamp.fromMillis(1)});
const lot=()=>({schemaVersion:2,material:'PCB',weightKg:2,city:'Ludhiana',status:'draft',createdAt:Timestamp.fromMillis(1),updatedAt:Timestamp.fromMillis(1),revision:1,activeRequestId:'',activeOfferId:'',photoStorage:'deviceOnly'});
const future=()=>Timestamp.fromMillis(Date.now()+3600000);
const db=(uid)=>env.authenticatedContext(uid).firestore();
const offerPath='recyclerRequests/r1/offers/c1_l1';
async function seed(path,value){await env.withSecurityRulesDisabled(async c=>setDoc(doc(c.firestore(),path),value));}
function proposal(){return {schemaVersion:2,collectorUid:'c1',lotId:'l1',material:'PCB',weightKg:2,status:'proposed',createdAt:serverTimestamp(),requestId:'r1',recyclerUid:'b1',recyclerName:'Test Buyer',city:'Ludhiana'};}
async function propose(d=db('c1')){const b=writeBatch(d);b.set(doc(d,offerPath),proposal());b.update(doc(d,'users/c1/lots/l1'),{status:'offered',activeRequestId:'r1',activeOfferId:'c1_l1',updatedAt:serverTimestamp()});return b.commit();}
async function quote(d=db('b1')){return updateDoc(doc(d,offerPath),{status:'quoted',quoteRate:100,quoteCurrency:'INR',quoteExpiresAt:future(),quotedAt:serverTimestamp()});}
async function accept(d=db('c1')){const b=writeBatch(d);b.update(doc(d,offerPath),{status:'accepted',acceptedAt:serverTimestamp()});b.update(doc(d,'users/c1/lots/l1'),{status:'reserved',updatedAt:serverTimestamp()});return b.commit();}
async function requestHandover(d=db('c1')){return updateDoc(doc(d,offerPath),{status:'handoverPending',handoverWeightKg:1.9,handoverRequestedAt:serverTimestamp()});}
async function complete(d=db('b1')){const b=writeBatch(d);b.update(doc(d,offerPath),{status:'completed',completedAt:serverTimestamp()});b.update(doc(d,'users/c1/lots/l1'),{status:'handedOver',updatedAt:serverTimestamp()});return b.commit();}
function receipt(){return {collectorUid:'c1',requestId:'r1',offerId:'c1_l1',amount:190,currency:'INR',method:'cash',reference:'Test only',kind:'collectorRecordedReceipt',createdAt:serverTimestamp()};}
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-kabadi-collector',firestore:{host:'127.0.0.1',port:8080,rules:readFileSync(new URL('../firestore_collector.rules',import.meta.url),'utf8')}});});
after(async()=>{await env?.cleanup();});
beforeEach(async()=>{await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{const d=c.firestore();const b=writeBatch(d);
  b.set(doc(d,'users/c1'),profile());b.set(doc(d,'users/c2'),profile());b.set(doc(d,'users/b1'),profile('recycler','verified'));b.set(doc(d,'users/b2'),profile('recycler','verified'));b.set(doc(d,'users/b3'),profile('recycler','pending'));
  b.set(doc(d,'users/c1/lots/l1'),lot());b.set(doc(d,'recyclerRequests/r1'),{status:'active',authorizationStatus:'verified',expiresAt:future(),recyclerUid:'b1',recyclerName:'Test Buyer',material:'PCB',city:'Ludhiana'});await b.commit();});});
test('own profile readable; other profile and unauthenticated access denied',async()=>{await assertSucceeds(getDoc(doc(db('c1'),'users/c1')));await assertFails(getDoc(doc(db('c2'),'users/c1')));await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(),'users/c1')));});
test('new valid contact profile allowed; no client authorization escalation',async()=>{const p={...profile(),createdAt:serverTimestamp(),updatedAt:serverTimestamp()};await assertSucceeds(setDoc(doc(db('new'),'users/new'),p));await assertFails(updateDoc(doc(db('c1'),'users/c1'),{authorizationStatus:'verified',updatedAt:serverTimestamp()}));await assertFails(updateDoc(doc(db('c1'),'users/c1'),{role:'recycler',updatedAt:serverTimestamp()}));});
test('invalid mobile and false verification claim rejected',async()=>{await assertFails(setDoc(doc(db('new'),'users/new'),{...profile(),mobileNumber:'123',createdAt:serverTimestamp(),updatedAt:serverTimestamp()}));await assertFails(updateDoc(doc(db('c1'),'users/c1'),{mobileVerified:true,updatedAt:serverTimestamp()}));});
test('owner can edit contact; cannot add a foreign email',async()=>{await assertSucceeds(updateDoc(doc(db('c1'),'users/c1'),{name:'New Name',mobileNumber:'+918765432109',mobileVerified:false,updatedAt:serverTimestamp()}));await assertFails(updateDoc(doc(db('c1'),'users/c1'),{email:'foreign@example.test',updatedAt:serverTimestamp()}));});
test('owner can add exact linked Auth email without changing UID',async()=>{const d=env.authenticatedContext('c1',{email:'owner@example.test'}).firestore();await assertSucceeds(updateDoc(doc(d,'users/c1'),{email:'owner@example.test',updatedAt:serverTimestamp()}));});
test('valid new lot and optimistic revision edit allowed',async()=>{const d=db('c1');await assertSucceeds(setDoc(doc(d,'users/c1/lots/l2'),{...lot(),createdAt:serverTimestamp(),updatedAt:serverTimestamp()}));await assertSucceeds(setDoc(doc(d,'users/c1/lots/l1'),{...lot(),weightKg:3,revision:2,updatedAt:serverTimestamp()}));});
test('invalid weight, stale revision, foreign lot write rejected',async()=>{await assertFails(setDoc(doc(db('c1'),'users/c1/lots/bad'),{...lot(),weightKg:0,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}));await assertFails(updateDoc(doc(db('c1'),'users/c1/lots/l1'),{weightKg:3,updatedAt:serverTimestamp()}));await assertFails(updateDoc(doc(db('c2'),'users/c1/lots/l1'),{status:'archived',updatedAt:serverTimestamp()}));});
test('collector cannot publish self-verified buyer request',async()=>{await assertFails(setDoc(doc(db('c1'),'recyclerRequests/forged'),{status:'active',authorizationStatus:'verified'}));});
test('proposal and lot lock succeed atomically',async()=>{await assertSucceeds(propose());});
test('proposal without lot lock rejected',async()=>{await assertFails(setDoc(doc(db('c1'),offerPath),proposal()));});
test('lot lock without corresponding offer rejected',async()=>{await assertFails(updateDoc(doc(db('c1'),'users/c1/lots/l1'),{status:'offered',activeRequestId:'r1',activeOfferId:'c1_l1',updatedAt:serverTimestamp()}));});
test('expired request rejects offer and preserves draft',async()=>{await seed('recyclerRequests/r1',{status:'active',authorizationStatus:'verified',expiresAt:Timestamp.fromMillis(1),recyclerUid:'b1',recyclerName:'Test Buyer',material:'PCB',city:'Ludhiana'});await assertFails(propose());});
test('revoked recycler rejects offer despite published verified snapshot',async()=>{await seed('users/b1',profile('recycler','pending'));await assertFails(propose());});
test('duplicate/second request and metadata editing cannot reuse locked lot',async()=>{await propose();await assertFails(propose());await assertFails(updateDoc(doc(db('c1'),'users/c1/lots/l1'),{weightKg:10,revision:2,updatedAt:serverTimestamp()}));});
test('only target verified buyer can quote, not collector or another buyer',async()=>{await propose();await assertFails(quote(db('c1')));await assertFails(quote(db('b2')));await assertSucceeds(quote());});
test('quote cannot overwrite collector weight or use negative rate',async()=>{await propose();await assertFails(updateDoc(doc(db('b1'),offerPath),{status:'quoted',quoteRate:-1,quoteCurrency:'INR',quoteExpiresAt:future(),quotedAt:serverTimestamp()}));await assertFails(updateDoc(doc(db('b1'),offerPath),{status:'quoted',weightKg:100,quoteRate:100,quoteCurrency:'INR',quoteExpiresAt:future(),quotedAt:serverTimestamp()}));});
test('accept requires paired reservation; collector cannot forge completion',async()=>{await propose();await quote();await assertFails(updateDoc(doc(db('c1'),offerPath),{status:'accepted',acceptedAt:serverTimestamp()}));await assertSucceeds(accept());await assertFails(updateDoc(doc(db('c1'),offerPath),{status:'completed',completedAt:serverTimestamp()}));});
test('revoked recycler blocks quote acceptance',async()=>{await propose();await quote();await seed('users/b1',profile('recycler','rejected'));await assertFails(accept());});
test('withdrawal releases lot atomically',async()=>{await propose();const d=db('c1');const b=writeBatch(d);b.update(doc(d,offerPath),{status:'cancelled',cancelledAt:serverTimestamp()});b.update(doc(d,'users/c1/lots/l1'),{status:'draft',activeRequestId:'',activeOfferId:'',updatedAt:serverTimestamp()});await assertSucceeds(b.commit());});
test('buyer rejection requires atomic release',async()=>{await propose();const d=db('b1');await assertFails(updateDoc(doc(d,offerPath),{status:'rejected',rejectedAt:serverTimestamp()}));const b=writeBatch(d);b.update(doc(d,offerPath),{status:'rejected',rejectedAt:serverTimestamp()});b.update(doc(d,'users/c1/lots/l1'),{status:'draft',activeRequestId:'',activeOfferId:'',updatedAt:serverTimestamp()});await assertSucceeds(b.commit());});
test('full two-party handover and receipt transaction succeed',async()=>{await propose();await quote();await accept();await requestHandover();await assertFails(complete(db('c1')));await assertSucceeds(complete());const d=db('c1');await assertSucceeds(runTransaction(d,async t=>{const p=doc(d,'collectorPayments/p1');const old=await t.get(p);if(!old.exists())t.set(p,receipt());}));});
test('receipt before handover, another owner, edits and bank-verification flag rejected',async()=>{await propose();await assertFails(setDoc(doc(db('c1'),'collectorPayments/p1'),receipt()));await quote();await accept();await requestHandover();await complete();await assertFails(setDoc(doc(db('c2'),'collectorPayments/p1'),receipt()));await assertFails(setDoc(doc(db('c1'),'collectorPayments/p1'),{...receipt(),bankVerified:true}));await setDoc(doc(db('c1'),'collectorPayments/p1'),receipt());await assertFails(updateDoc(doc(db('c1'),'collectorPayments/p1'),{amount:999}));});
test('offers group query owner-filtered only; buyer cannot list unrelated lot collection',async()=>{await propose();const d=db('c1');await assertSucceeds(getDocs(query(collectionGroup(d,'offers'),where('collectorUid','==','c1'),orderBy('createdAt','desc'))));await assertFails(getDocs(collectionGroup(d,'offers')));await assertFails(getDocs(collection(db('b1'),'users/c1/lots')));await assertSucceeds(getDoc(doc(db('b1'),'users/c1/lots/l1')));});
test('legacy profile and lot remain readable; legacy lot can be deliberately migrated',async()=>{const p=profile();delete p.mobileNumber;delete p.mobileVerified;await seed('users/c1',p);await assertSucceeds(getDoc(doc(db('c1'),'users/c1')));await seed('users/c1/lots/old',{material:'PCB',weightKg:2,city:'Ludhiana',status:'draft',createdAt:Timestamp.fromMillis(1)});await assertSucceeds(setDoc(doc(db('c1'),'users/c1/lots/old'),{...lot(),updatedAt:serverTimestamp()}));});

test('buyer can list own requests and nested offers, not another buyer requests',async()=>{await propose();await assertSucceeds(getDocs(query(collection(db('b1'),'recyclerRequests'),where('recyclerUid','==','b1'))));await assertSucceeds(getDocs(collection(db('b1'),'recyclerRequests/r1/offers')));await assertFails(getDocs(query(collection(db('b2'),'recyclerRequests'),where('recyclerUid','==','b1'))));});
test('collector active-demand query works; unfiltered request listing denied',async()=>{await assertSucceeds(getDocs(query(collection(db('c1'),'recyclerRequests'),where('status','==','active'),where('authorizationStatus','==','verified'))));await assertFails(getDocs(collection(db('c1'),'recyclerRequests')));});
test('receipt query is owner filtered and cannot expose another collector',async()=>{await propose();await quote();await accept();await requestHandover();await complete();await setDoc(doc(db('c1'),'collectorPayments/p1'),receipt());await assertSucceeds(getDocs(query(collection(db('c1'),'collectorPayments'),where('collectorUid','==','c1'),orderBy('createdAt','desc'))));await assertFails(getDoc(doc(db('c2'),'collectorPayments/p1')));await assertFails(getDocs(collection(db('c1'),'collectorPayments')));});
